// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {
      '404': { id: '404', path: '*', parentId: 'DocLayout' },
      'dumi-context-layout': { id: 'dumi-context-layout', path: '/', isLayout: true },
      DocLayout: { id: 'DocLayout', path: '/', parentId: 'dumi-context-layout', isLayout: true },
      'docs/guide/zcontribute.zh-CN': {
        path: 'guide/zcontribute',
        id: 'docs/guide/zcontribute.zh-CN',
        parentId: 'DocLayout',
      },
      'docs/guide/introduce.zh-CN': {
        path: 'guide/introduce',
        id: 'docs/guide/introduce.zh-CN',
        parentId: 'DocLayout',
      },
      'docs/guide/xproject.zh-CN': {
        path: 'guide/xproject',
        id: 'docs/guide/xproject.zh-CN',
        parentId: 'DocLayout',
      },
      'docs/guide/yproject.zh-CN': {
        path: 'guide/yproject',
        id: 'docs/guide/yproject.zh-CN',
        parentId: 'DocLayout',
      },
      'docs/guide/vcolor.zh-CN': {
        path: 'guide/vcolor',
        id: 'docs/guide/vcolor.zh-CN',
        parentId: 'DocLayout',
      },
      'docs/guide/vscode.zh-CN': {
        path: 'guide/vscode',
        id: 'docs/guide/vscode.zh-CN',
        parentId: 'DocLayout',
      },
      'docs/guide/wclass.zh-CN': {
        path: 'guide/wclass',
        id: 'docs/guide/wclass.zh-CN',
        parentId: 'DocLayout',
      },
      'docs/guide/wtheme.zh-CN': {
        path: 'guide/wtheme',
        id: 'docs/guide/wtheme.zh-CN',
        parentId: 'DocLayout',
      },
      'docs/guide/teuse.zh-CN': {
        path: 'guide/teuse',
        id: 'docs/guide/teuse.zh-CN',
        parentId: 'DocLayout',
      },
      'docs/guide/udark.zh-CN': {
        path: 'guide/udark',
        id: 'docs/guide/udark.zh-CN',
        parentId: 'DocLayout',
      },
      'docs/guide/wvite.zh-CN': {
        path: 'guide/wvite',
        id: 'docs/guide/wvite.zh-CN',
        parentId: 'DocLayout',
      },
      'docs/guide/zcontribute': {
        path: 'guide/zcontribute',
        id: 'docs/guide/zcontribute',
        parentId: 'DocLayout',
      },
      'docs/guide/introduce': {
        path: 'guide/introduce',
        id: 'docs/guide/introduce',
        parentId: 'DocLayout',
      },
      'docs/guide/xproject': {
        path: 'guide/xproject',
        id: 'docs/guide/xproject',
        parentId: 'DocLayout',
      },
      'docs/guide/yproject': {
        path: 'guide/yproject',
        id: 'docs/guide/yproject',
        parentId: 'DocLayout',
      },
      'docs/guide/vcolor': { path: 'guide/vcolor', id: 'docs/guide/vcolor', parentId: 'DocLayout' },
      'docs/guide/vscode': { path: 'guide/vscode', id: 'docs/guide/vscode', parentId: 'DocLayout' },
      'docs/guide/wclass': { path: 'guide/wclass', id: 'docs/guide/wclass', parentId: 'DocLayout' },
      'docs/guide/wtheme': { path: 'guide/wtheme', id: 'docs/guide/wtheme', parentId: 'DocLayout' },
      'docs/guide/teuse': { path: 'guide/teuse', id: 'docs/guide/teuse', parentId: 'DocLayout' },
      'docs/guide/udark': { path: 'guide/udark', id: 'docs/guide/udark', parentId: 'DocLayout' },
      'docs/guide/wvite': { path: 'guide/wvite', id: 'docs/guide/wvite', parentId: 'DocLayout' },
      'docs/index.zh-CN': { path: '', id: 'docs/index.zh-CN', parentId: 'DocLayout' },
      'docs/index': { path: '', id: 'docs/index', parentId: 'DocLayout' },
      'demo-render': { id: 'demo-render', path: '~demos/:id', parentId: 'dumi-context-layout' },
    },
    routeComponents: {
      '404': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__registry.npmmirror.com+dumi_2.0.2_ytirsdfjrd6qitzvcje6fgo3mq__node_modules__dumi__dist__client__pages__404" */ '/Users/apple/Desktop/Concis/node_modules/.pnpm/registry.npmmirror.com+dumi@2.0.2_ytirsdfjrd6qitzvcje6fgo3mq/node_modules/dumi/dist/client/pages/404.js'
          )
      ),
      'dumi-context-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */ '/Users/apple/Desktop/Concis/.dumi/tmp/dumi/theme/ContextWrapper.tsx'
          )
      ),
      DocLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__registry.npmmirror.com+dumi_2.0.2_ytirsdfjrd6qitzvcje6fgo3mq__node_modules__dumi__theme-default__layouts__DocLayout__index" */ '/Users/apple/Desktop/Concis/node_modules/.pnpm/registry.npmmirror.com+dumi@2.0.2_ytirsdfjrd6qitzvcje6fgo3mq/node_modules/dumi/theme-default/layouts/DocLayout/index.js'
          )
      ),
      'docs/guide/zcontribute.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__zcontribute.zh-CN.md" */ '/Users/apple/Desktop/Concis/docs/guide/zcontribute.zh-CN.md'
          )
      ),
      'docs/guide/introduce.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__introduce.zh-CN.md" */ '/Users/apple/Desktop/Concis/docs/guide/introduce.zh-CN.md'
          )
      ),
      'docs/guide/xproject.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__xproject.zh-CN.md" */ '/Users/apple/Desktop/Concis/docs/guide/xproject.zh-CN.md'
          )
      ),
      'docs/guide/yproject.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__yproject.zh-CN.md" */ '/Users/apple/Desktop/Concis/docs/guide/yproject.zh-CN.md'
          )
      ),
      'docs/guide/vcolor.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__vcolor.zh-CN.md" */ '/Users/apple/Desktop/Concis/docs/guide/vcolor.zh-CN.md'
          )
      ),
      'docs/guide/vscode.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__vscode.zh-CN.md" */ '/Users/apple/Desktop/Concis/docs/guide/vscode.zh-CN.md'
          )
      ),
      'docs/guide/wclass.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__wclass.zh-CN.md" */ '/Users/apple/Desktop/Concis/docs/guide/wclass.zh-CN.md'
          )
      ),
      'docs/guide/wtheme.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__wtheme.zh-CN.md" */ '/Users/apple/Desktop/Concis/docs/guide/wtheme.zh-CN.md'
          )
      ),
      'docs/guide/teuse.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__teuse.zh-CN.md" */ '/Users/apple/Desktop/Concis/docs/guide/teuse.zh-CN.md'
          )
      ),
      'docs/guide/udark.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__udark.zh-CN.md" */ '/Users/apple/Desktop/Concis/docs/guide/udark.zh-CN.md'
          )
      ),
      'docs/guide/wvite.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__wvite.zh-CN.md" */ '/Users/apple/Desktop/Concis/docs/guide/wvite.zh-CN.md'
          )
      ),
      'docs/guide/zcontribute': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__zcontribute.md" */ '/Users/apple/Desktop/Concis/docs/guide/zcontribute.md'
          )
      ),
      'docs/guide/introduce': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__introduce.md" */ '/Users/apple/Desktop/Concis/docs/guide/introduce.md'
          )
      ),
      'docs/guide/xproject': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__xproject.md" */ '/Users/apple/Desktop/Concis/docs/guide/xproject.md'
          )
      ),
      'docs/guide/yproject': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__yproject.md" */ '/Users/apple/Desktop/Concis/docs/guide/yproject.md'
          )
      ),
      'docs/guide/vcolor': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__vcolor.md" */ '/Users/apple/Desktop/Concis/docs/guide/vcolor.md'
          )
      ),
      'docs/guide/vscode': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__vscode.md" */ '/Users/apple/Desktop/Concis/docs/guide/vscode.md'
          )
      ),
      'docs/guide/wclass': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__wclass.md" */ '/Users/apple/Desktop/Concis/docs/guide/wclass.md'
          )
      ),
      'docs/guide/wtheme': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__wtheme.md" */ '/Users/apple/Desktop/Concis/docs/guide/wtheme.md'
          )
      ),
      'docs/guide/teuse': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__teuse.md" */ '/Users/apple/Desktop/Concis/docs/guide/teuse.md'
          )
      ),
      'docs/guide/udark': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__udark.md" */ '/Users/apple/Desktop/Concis/docs/guide/udark.md'
          )
      ),
      'docs/guide/wvite': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__wvite.md" */ '/Users/apple/Desktop/Concis/docs/guide/wvite.md'
          )
      ),
      'docs/index.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__index.zh-CN.md" */ '/Users/apple/Desktop/Concis/docs/index.zh-CN.md'
          )
      ),
      'docs/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__index.md" */ '/Users/apple/Desktop/Concis/docs/index.md'
          )
      ),
      'demo-render': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__registry.npmmirror.com+dumi_2.0.2_ytirsdfjrd6qitzvcje6fgo3mq__node_modules__dumi__dist__client__pages__Demo__index" */ '/Users/apple/Desktop/Concis/node_modules/.pnpm/registry.npmmirror.com+dumi@2.0.2_ytirsdfjrd6qitzvcje6fgo3mq/node_modules/dumi/dist/client/pages/Demo/index.js'
          )
      ),
    },
  };
}
