// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/apple/Desktop/Concis/node_modules/.pnpm/registry.npmmirror.com+dumi@2.0.2_ytirsdfjrd6qitzvcje6fgo3mq/node_modules/dumi/theme-default/slots/Navbar/index.js';
