// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import {
  demos as dm0,
  frontmatter as fm0,
  toc as toc0,
  texts as txt0,
} from '/Users/apple/Desktop/Concis/docs/guide/zcontribute.zh-CN.md?type=meta';
import {
  demos as dm1,
  frontmatter as fm1,
  toc as toc1,
  texts as txt1,
} from '/Users/apple/Desktop/Concis/docs/guide/introduce.zh-CN.md?type=meta';
import {
  demos as dm2,
  frontmatter as fm2,
  toc as toc2,
  texts as txt2,
} from '/Users/apple/Desktop/Concis/docs/guide/xproject.zh-CN.md?type=meta';
import {
  demos as dm3,
  frontmatter as fm3,
  toc as toc3,
  texts as txt3,
} from '/Users/apple/Desktop/Concis/docs/guide/yproject.zh-CN.md?type=meta';
import {
  demos as dm4,
  frontmatter as fm4,
  toc as toc4,
  texts as txt4,
} from '/Users/apple/Desktop/Concis/docs/guide/vcolor.zh-CN.md?type=meta';
import {
  demos as dm5,
  frontmatter as fm5,
  toc as toc5,
  texts as txt5,
} from '/Users/apple/Desktop/Concis/docs/guide/vscode.zh-CN.md?type=meta';
import {
  demos as dm6,
  frontmatter as fm6,
  toc as toc6,
  texts as txt6,
} from '/Users/apple/Desktop/Concis/docs/guide/wclass.zh-CN.md?type=meta';
import {
  demos as dm7,
  frontmatter as fm7,
  toc as toc7,
  texts as txt7,
} from '/Users/apple/Desktop/Concis/docs/guide/wtheme.zh-CN.md?type=meta';
import {
  demos as dm8,
  frontmatter as fm8,
  toc as toc8,
  texts as txt8,
} from '/Users/apple/Desktop/Concis/docs/guide/teuse.zh-CN.md?type=meta';
import {
  demos as dm9,
  frontmatter as fm9,
  toc as toc9,
  texts as txt9,
} from '/Users/apple/Desktop/Concis/docs/guide/udark.zh-CN.md?type=meta';
import {
  demos as dm10,
  frontmatter as fm10,
  toc as toc10,
  texts as txt10,
} from '/Users/apple/Desktop/Concis/docs/guide/wvite.zh-CN.md?type=meta';
import {
  demos as dm11,
  frontmatter as fm11,
  toc as toc11,
  texts as txt11,
} from '/Users/apple/Desktop/Concis/docs/guide/zcontribute.md?type=meta';
import {
  demos as dm12,
  frontmatter as fm12,
  toc as toc12,
  texts as txt12,
} from '/Users/apple/Desktop/Concis/docs/guide/introduce.md?type=meta';
import {
  demos as dm13,
  frontmatter as fm13,
  toc as toc13,
  texts as txt13,
} from '/Users/apple/Desktop/Concis/docs/guide/xproject.md?type=meta';
import {
  demos as dm14,
  frontmatter as fm14,
  toc as toc14,
  texts as txt14,
} from '/Users/apple/Desktop/Concis/docs/guide/yproject.md?type=meta';
import {
  demos as dm15,
  frontmatter as fm15,
  toc as toc15,
  texts as txt15,
} from '/Users/apple/Desktop/Concis/docs/guide/vcolor.md?type=meta';
import {
  demos as dm16,
  frontmatter as fm16,
  toc as toc16,
  texts as txt16,
} from '/Users/apple/Desktop/Concis/docs/guide/vscode.md?type=meta';
import {
  demos as dm17,
  frontmatter as fm17,
  toc as toc17,
  texts as txt17,
} from '/Users/apple/Desktop/Concis/docs/guide/wclass.md?type=meta';
import {
  demos as dm18,
  frontmatter as fm18,
  toc as toc18,
  texts as txt18,
} from '/Users/apple/Desktop/Concis/docs/guide/wtheme.md?type=meta';
import {
  demos as dm19,
  frontmatter as fm19,
  toc as toc19,
  texts as txt19,
} from '/Users/apple/Desktop/Concis/docs/guide/teuse.md?type=meta';
import {
  demos as dm20,
  frontmatter as fm20,
  toc as toc20,
  texts as txt20,
} from '/Users/apple/Desktop/Concis/docs/guide/udark.md?type=meta';
import {
  demos as dm21,
  frontmatter as fm21,
  toc as toc21,
  texts as txt21,
} from '/Users/apple/Desktop/Concis/docs/guide/wvite.md?type=meta';
import {
  demos as dm22,
  frontmatter as fm22,
  toc as toc22,
  texts as txt22,
} from '/Users/apple/Desktop/Concis/docs/index.zh-CN.md?type=meta';
import {
  demos as dm23,
  frontmatter as fm23,
  toc as toc23,
  texts as txt23,
} from '/Users/apple/Desktop/Concis/docs/index.md?type=meta';

export { components } from './atoms';
export { tabs } from './tabs';

export const filesMeta = {
  'docs/guide/zcontribute.zh-CN': {
    frontmatter: fm0,
    toc: toc0,
    texts: txt0,
    demos: dm0,
  },
  'docs/guide/introduce.zh-CN': {
    frontmatter: fm1,
    toc: toc1,
    texts: txt1,
    demos: dm1,
  },
  'docs/guide/xproject.zh-CN': {
    frontmatter: fm2,
    toc: toc2,
    texts: txt2,
    demos: dm2,
  },
  'docs/guide/yproject.zh-CN': {
    frontmatter: fm3,
    toc: toc3,
    texts: txt3,
    demos: dm3,
  },
  'docs/guide/vcolor.zh-CN': {
    frontmatter: fm4,
    toc: toc4,
    texts: txt4,
    demos: dm4,
  },
  'docs/guide/vscode.zh-CN': {
    frontmatter: fm5,
    toc: toc5,
    texts: txt5,
    demos: dm5,
  },
  'docs/guide/wclass.zh-CN': {
    frontmatter: fm6,
    toc: toc6,
    texts: txt6,
    demos: dm6,
  },
  'docs/guide/wtheme.zh-CN': {
    frontmatter: fm7,
    toc: toc7,
    texts: txt7,
    demos: dm7,
  },
  'docs/guide/teuse.zh-CN': {
    frontmatter: fm8,
    toc: toc8,
    texts: txt8,
    demos: dm8,
  },
  'docs/guide/udark.zh-CN': {
    frontmatter: fm9,
    toc: toc9,
    texts: txt9,
    demos: dm9,
  },
  'docs/guide/wvite.zh-CN': {
    frontmatter: fm10,
    toc: toc10,
    texts: txt10,
    demos: dm10,
  },
  'docs/guide/zcontribute': {
    frontmatter: fm11,
    toc: toc11,
    texts: txt11,
    demos: dm11,
  },
  'docs/guide/introduce': {
    frontmatter: fm12,
    toc: toc12,
    texts: txt12,
    demos: dm12,
  },
  'docs/guide/xproject': {
    frontmatter: fm13,
    toc: toc13,
    texts: txt13,
    demos: dm13,
  },
  'docs/guide/yproject': {
    frontmatter: fm14,
    toc: toc14,
    texts: txt14,
    demos: dm14,
  },
  'docs/guide/vcolor': {
    frontmatter: fm15,
    toc: toc15,
    texts: txt15,
    demos: dm15,
  },
  'docs/guide/vscode': {
    frontmatter: fm16,
    toc: toc16,
    texts: txt16,
    demos: dm16,
  },
  'docs/guide/wclass': {
    frontmatter: fm17,
    toc: toc17,
    texts: txt17,
    demos: dm17,
  },
  'docs/guide/wtheme': {
    frontmatter: fm18,
    toc: toc18,
    texts: txt18,
    demos: dm18,
  },
  'docs/guide/teuse': {
    frontmatter: fm19,
    toc: toc19,
    texts: txt19,
    demos: dm19,
  },
  'docs/guide/udark': {
    frontmatter: fm20,
    toc: toc20,
    texts: txt20,
    demos: dm20,
  },
  'docs/guide/wvite': {
    frontmatter: fm21,
    toc: toc21,
    texts: txt21,
    demos: dm21,
  },
  'docs/index.zh-CN': {
    frontmatter: fm22,
    toc: toc22,
    texts: txt22,
    demos: dm22,
  },
  'docs/index': {
    frontmatter: fm23,
    toc: toc23,
    texts: txt23,
    demos: dm23,
  },
};

// generate demos data in runtime, for reuse route.id to reduce bundle size
export const demos = Object.entries(filesMeta).reduce((acc, [id, meta]) => {
  // append route id to demo
  Object.values(meta.demos).forEach((demo) => {
    demo.routeId = id;
  });
  // merge demos
  Object.assign(acc, meta.demos);

  // remove demos from meta, to avoid deep clone demos in umi routes/children compatible logic
  delete meta.demos;

  return acc;
}, {});
